### PR TITLE
Add ROOT hackerspace

### PR DESCRIPTION
**Pull request by frapposelli**
greetings from Italy :it:

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks for the entry! Unfortunately the certificate is self-signed. Do you plan to fix that?

Furthermore, the endpoint has no CORS headers set. It would be helpful if that would be the case, since otherwise JavaScript applications cannot fetch your endpoint.



You can validate the endpoint with https://spaceapi.io/pages/validator.html. Usually just adding a `Access-Control-Allow-Origin: *` header is sufficient.

**Comment by frapposelli** [comment]
Certificate will be fixed once we set up DNS properly, so yes, it's coming 😄 

I just validated the endpoint with the link you've provided, and it validates correctly, the code that generates the JSON should output the CORS header https://github.com/rootclub/peronibot/blob/master/cmd/server/server.go#L99-L107

**Comment by dbrgn** [comment]
> Certificate will be fixed once we set up DNS properly, so yes, it's coming

Great to hear, then let's wait with merging until DNS is set up :slightly_smiling_face: Self-signed certificates may confuse applications that parse the directory.

**Comment by frapposelli** [comment]
@dbrgn we should be all set now 👍

**Comment by dbrgn** [comment]
Looks great :slightly_smiling_face:

**Pull request merged**
