### PR TITLE
Adding Arch Reactor

### PR DESCRIPTION
**Pull request by Chankster**

### CODE REVIEW

**Comment by rorist** [comment]
Hello, the endpoint returns nothing.

```
$ curl https://archreactor.org/status.php -i
HTTP/1.1 200 OK
Date: Fri, 20 Jan 2017 21:22:10 GMT
Server: Apache
Content-Length: 0
Content-Type: text/html; charset=UTF-8
```

**Comment by Chankster** [comment]
Apologies, submitted the PR before getting the code saved on our server.  I also got the backslashes updated.

**Comment by dns2utf8** [comment]
I used your space for the development of the new [verification tools](https://github.com/spacedirectory/validator) and noticed some flaws:
  * the field API is wrong. Should be "0.13"
  * there is no logo field
  * the server does not send any CORS headers.

I am working on the tools right now, they should be available soon.
Currently you will have to use the validator locally if you would like to test it yourself.

**Comment by Chankster** [comment]
I can get the items above fixed, but I can't seem to get the validator to work.  It just displays "Fetching data, please hold . . .".  The cargo service does appear to be running and hitting http://localhost:6767 returns "OK".

**Comment by dns2utf8** [comment]
I guess these errors have not made it into master yet.
Can you use the branch `cleanup`?

**Pull request merged**
