### PR TITLE
Added Spline

### PR DESCRIPTION
**Pull request by Centzilius**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi. Thanks for the PR!

However, it seems that CORS is not enabled on your server, meaning that JavaScript applications cannot query your endpoint. Usually just adding a access-control-allow-origin: * header to the webserver should be sufficient.

Could you check? You can validate the endpoint with https://spaceapi.io/pages/validator.html. Would it be possible to set up CORS?

**Comment by Centzilius** [comment]
Hi.
Cors is in fact enabled but the validator is not forking due to mixed content (as the API is currently only reachable via HTTP). I'll contact our CA wizard and will enable https and add another commit to this PR.

```
cent@hinako ~ % curl -i http://iot.spline.de/api/status.json
HTTP/1.1 200 OK
Date: Sat, 04 May 2019 18:39:42 GMT
Server: Apache/2.2.22 (Debian)
Last-Modified: Fri, 03 May 2019 18:36:13 GMT
ETag: "520008-2a9-5880006763bd3"
Accept-Ranges: bytes
Content-Length: 681
Access-Control-Allow-Origin: *
Content-Type: application/json

{
  "api": "0.13",
  "space": "Spline",
  "logo": "https://www.spline.de/logo/png/spline-logo-full-white-transp.png",
  "url": "https://spline.de",
  "location": {
    "address": "Takustr. 9, 14195 Berlin, Germany",
    "lon": 52.455949,
    "lat": 13.297178
  },
  "contact": {
    "email": "spline@spline.de",
    "irc": "irc://irc.freenode.net/spline",
    "ml": "splie@lists.spline.de",
    "twitter": "@SplineFU"
  },
  "issue_report_channels": [
    "ml"
  ],
  "state": {
    "icon": {
      "open": "https://www.spline.de/logo/png/spline-logo-min-black-transp.png",
      "closed": "https://www.spline.de/logo/png/spline-logo-min-white-transp.png"
    },
"open": true
}
}
```

**Comment by dbrgn** [comment]
Oh, you're right :slightly_smiling_face: Sorry, I should have checked more closely.

**Comment by Centzilius** [comment]
HTTPs has been enabled and we should be ready to go

**Comment by dbrgn** [comment]
Cool, thanks!

**Pull request merged**
