### PR TITLE
Adding xHain from Berlin

### PR DESCRIPTION
**Pull request by AnsgarSchmidt**

### CODE REVIEW

**Comment by rorist** [comment]
Hi, your certificate isn't valid for your domain, you should allow acces from the github URL without redirection ? https://xHain-hackspace.github.io/spaceapi-0.13.json

It's not really blocking for myhackerspace app, as we're using trustmemorize 3rd party to allow untrusted cert, but still would be better to avoid that imho.

**Comment by AnsgarSchmidt** [comment]
Hi, we are transferring everything in the next days from github to our own server with a letsencrypt certificate. So for now the certificate is broken because we serve from github but this will be fixed in the next days.

**Comment by rorist** [comment]
ok cool :)

**Comment by AnsgarSchmidt** [comment]
Thanks a lot!

**Pull request merged**
