### PR TITLE
Added Pixelbar (NL)

### PR DESCRIPTION
**Pull request by xopr**
Found a Dutch hackerspace who's spaceAPI URI was hard to find (found at https://github.com/zeno4ever/hsmap/blob/master/hsmap.php )

### CODE REVIEW

**Comment by rorist** [comment]
Hi, the CI had problem accessing your endpoint with the error `[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)`, is it familiar for you ? it seems ok from my machine though.

**Comment by xopr** [comment]
Hmm, I did some research, and apparently, the certificate is issued by StartCom, which seems to be owned by WoSign, which Mozilla started to distrust recently due to mismanagement.
I tried to connect to non-ssl, but it redirects me.
Not sure how to move forward with this (I'm not part of that hackerspace, just visited it once)

**Comment by rorist** [comment]
Ah okay, it's not really problematic, but if you have the opportunity it
would be wise to tell them to use LetsEncrypt :)

Mergin'..

**Comment by xopr** [comment]
Thanks!

**Pull request merged**
