### PR TITLE
Add Mittelab hackerspace

### PR DESCRIPTION
**Pull request by g5pw**
Thanks! Just a static JSON for now, hopefully something more clever in the future!

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! Static JSON is perfectly fine :slightly_smiling_face: 

However, it seems that CORS is not enabled on your server, meaning that JavaScript applications cannot query your endpoint.

Could you check? You can validate the endpoint with https://spaceapi.io/pages/validator.html. Would it be possible to set up CORS? Usually just adding a `Access-Control-Allow-Origin: *` header should be sufficient.

**Comment by g5pw** [comment]
Oh right! I actually noticed the CORS error, but thought that since the app queries the JSON directly, it was not necessary, but if you're querying from JS it's actually needed! I'll add that ASAP.

**Comment by g5pw** [comment]
Should be working now!

**Comment by dbrgn** [comment]
Thanks, looks good now!

**Pull request merged**
