### PR TITLE
add new Hackspace UN-Hack-Bar

### PR DESCRIPTION
**Pull request by flashfingaz**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi. Thanks for the entry!

Your webserver does not set CORS headers, that means that JavaScript applications cannot fetch your endpoint. Can you add the following HTTP header to the server when serving the SpaceAPI file?

    Access-Control-Allow-Origin: *

Thanks!

**Comment by flashfingaz** [comment]
has been fixed, please check again!

**Comment by dbrgn** [comment]
Great, thanks :slightly_smiling_face:

**Comment by flashfingaz** [comment]
thx! =)

**Pull request merged**
