### PR TITLE
Adding MakeRiga hackerspace

### PR DESCRIPTION
**Pull request by CRImier**
No state yet, but will be adding that as soon as we have the infrastructure in place

### CODE REVIEW

**Comment by rnestler** [comment]
Since the old link doesn't work and the new one does I think this is good to merge :)

**Comment by CRImier** [comment]
Wrong PR, think you meant to comment on #97

**Comment by rnestler** [comment]
> Wrong PR, think you meant to comment on #97

Yes, sorry :man_facepalming:

**Comment by rnestler** [comment]
@CRImier The link works and content looks sane, but CORS headers aren't set, that limits the use in web applications. For example the validator fails to fetch it: https://spaceapi.io/pages/validator.html.

**Comment by rnestler** [comment]
@CRImier The `issue_report_channels` fields should not include `irc` since only `['email', 'issue_mail', 'twitter', 'ml']` are allowed there.

Apart from that it looks good to me :slightly_smiling_face:

**Comment by CRImier** [comment]
ah. Well, it actually is the most efficient channel for resolving issues ;-P Currently trying to make CORS work, will ping you as soon as it's ready and working with the validator

**Comment by dbrgn** [comment]
@CRImier do you plan to add HTTPS support? Missing support for HTTPS limits the use from web based clients because the requests may be blocked otherwise due to mixed content policies.

**Comment by rnestler** [comment]
> Currently trying to make CORS work, will ping you as soon as it's ready and working with the validator

I don't think it's due to CORS, I think the headers there are fine:
```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
Access-Control-Expose-Headers: Content-Length,Content-Range
```
The issue was with it being blocked due to mixed content (https and http). Deactivating it made it load in the validator.

**Comment by CRImier** [comment]
Ahh, this makes sense. Will set LE up and report back.

**Comment by CRImier** [comment]
Done, validator seems to work! Let me know if there are any other issues. Also, why is IRC not a good format for issues?

**Comment by dbrgn** [comment]
> Done, validator seems to work!

Thanks! Can you also update the URL in this PR to use https?

> Also, why is IRC not a good format for issues?

It simply isn't part of the [spec](https://spaceapi.io/pages/docs.html) :slightly_smiling_face: If you think it should be, you could propose it [here](https://github.com/SpaceApi/schema).

**Comment by CRImier** [comment]
URL updated - hope you're OK with an additional commit instead of a squashed one. Will also open a proposal, thank you for the info!

**Comment by dbrgn** [comment]
Perfect, thanks @CRImier! Yes, an additional commit is OK, we usually squash on merge anyways :slightly_smiling_face:

**Comment by CRImier** [comment]
Read the spec, thought about it, the IRC suggestion isn't all that important - esp. given it's to be used only for SpaceAPI stuff. So, I don't think the proposal would be useful - esp. given there would likely be effort required from your part => I won't be making it.

**Pull request merged**
