### PR TITLE
updates entry for hackzogtum

### PR DESCRIPTION
**Pull request by legion151**

### CODE REVIEW

**Comment by rorist** [comment]
Hello,

What is the reason of this change ? The old entry is still valid, but it leads to a different IP, plus the old entry is ipv6 compatible, but the new version with the ipv4 only isn't.

```
$ host mmisc.de
mmisc.de has address 144.76.70.237
mmisc.de has IPv6 address 2a01:4f8:191:83ec::2
mmisc.de mail is handled by 0 core.stw-bonn.de.
```

Cheers

**Comment by legion151** [comment]
We're leaving the current server and moving everything to a vhost. the old url will get invalid soon and i was not sure how long it will take here to accept the change. i will , when everything is done, make a new request changing to the ip to a url again.

**Comment by rorist** [comment]
The ttl for the zone is already low, so hopefully the migration should be pretty fast, isn't it ?

**Comment by legion151** [comment]
giving up on that one. the ttl is low yes - but the url and path also changed. there is a new pull request -> closing this one.

**Pull request closed without merging**
