### PR TITLE
Update AFRA

### PR DESCRIPTION
**Pull request by zeltophil**

### CODE REVIEW

**Comment by dbrgn** [comment]
Hi. Thanks for the update!

However, it seems that CORS is not enabled on your server, meaning that JavaScript applications cannot query your endpoint. Usually just adding a `access-control-allow-origin: *` header to the webserver should be sufficient.

Could you check? You can validate the endpoint with https://spaceapi.io/pages/validator.html. Would it be possible to set up CORS?

**Comment by lynxis** [comment]
CORS are now enabled.

**Comment by lynxis** [comment]
@dbrgn the validator says `{"valid": true, "message": null}`

**Comment by dbrgn** [comment]
Sorry, I was sick for the last few days.

Looks good now, thanks!

**Comment by zeltophil** [comment]
@dbrgn Thank you!

**Pull request merged**
